HairSalon/Models/Client.cs
using System.Collections.Generic;

namespace HairSalon.Models
{
  public class Client
  {
    public int ClientId { get; set; }
    public string Name { get; set; }
    public int StylistId { get; set; }
    public virtual Stylist Stylist { get; set; }
  }
} 

HairSalon/Models/HairSalonContext.cs
using Microsoft.EntityFrameworkCore;

namespace HairSalon.Models
{
  public class HairSalonContext : DbContext
  {
    public DbSet<Client> Clients { get; set; }
    public DbSet<Stylist> Stylists { get; set; }
    public HairSalonContext(DbContextOptions options) : base(options) { }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
      {
          optionsBuilder.UseLazyLoadingProxies();
      }
  }  
}

HairSalon/Models/Stylist.cs
using System.Collections.Generic;
using HairSalon.Models;

namespace HairSalon.Models
{
  public class Stylist
  {
    public Stylist()
    {
      this.ClientList = new HashSet<Client>();
    }
    public int StylistId { get; set; }
    public string Name { get; set; }

    //this is their specialty e.g. "Color", "Womens hair", "Mens hair", "Curly", etc.
    public string Skill { get; set; }
    public virtual ICollection<Client> ClientList { get; set; }

  }
}

HairSalon/Controllers/ClientsController.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using HairSalon.Models;
using System.Collections.Generic;
using System.Linq;

using Microsoft.AspNetCore.Mvc.Rendering;

namespace HairSalon.Controllers
{
  public class ClientsController : Controller
  {
    private readonly HairSalonContext _db;

    public ClientsController(HairSalonContext dbClient)
    {
      _db = dbClient;
    }

     public ActionResult Index()
    {
      // List<Client> model = _db.Clients.Include(client =>  client.ClientId).ToList();
      // return View(model);
      List<Client> model = _db.Clients.ToList();
      return View(model);
    }

    public ActionResult Add()
    {
      ViewBag.StylistId = new SelectList(_db.Stylists, "StylistId", "Name");
      return View();
    }

    [HttpPost]
    public ActionResult Add(Client client)
    {
      _db.Clients.Add(client);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult Details(int id)
    {
      Client currentClient = _db.Clients.FirstOrDefault(Client => Client.ClientId == id);
      ViewBag.StylistId = new SelectList(_db.Stylists, "StylistId", "Name");
      return View(currentClient);
    }

    [HttpPost]
    public ActionResult Details()
    {
      // var selectedStylist = _db.Stylists.FirstOrDefault(styler => styler.StylistId == stylistIdNew);
      ViewBag.StylistId = new SelectList(_db.Stylists, "StylistId", "Name");
      return RedirectToAction("Index", "Home");
    }
  

  }
}

HairSalon/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace HairSalon.Controllers
{
    public class HomeController : Controller
    {

      [HttpGet("/")]
      public ActionResult Index()
      {
        return View();
      }

    }
}

HairSalon/Controllers/StylistsController.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using HairSalon.Models;
using System.Collections.Generic;
using System.Linq;

namespace HairSalon.Controllers
{
  public class StylistsController : Controller
  {
    private readonly HairSalonContext _db;

    public StylistsController(HairSalonContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Stylist> model = _db.Stylists.ToList();
      return View(model);
    }

    public ActionResult Add()
    {
      return View();
    }

    //instantiate new stylist, auto increments Id, adds to _db
    [HttpPost]
    public ActionResult Add(Stylist stylist)
    {
      _db.Stylists.Add(stylist);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult Details(int id)
    {
      Stylist currentStylist = _db.Stylists.FirstOrDefault(stylist => stylist.StylistId == id);
      return View(currentStylist);
    }

    public ActionResult AddClient()
    {
      return RedirectToAction("Add", "Clients");
    }
    
    public ActionResult SelectStylist()
    {
  
      return View();
    }
    

    [HttpPost]
    public ActionResult SelectStylistPost(Client client, int id)
    {
      var selectedStylist = _db.Stylists.FirstOrDefault(styler => styler.StylistId == id);
      _db.Clients.Add(client);
      return View(selectedStylist);
    }
  
  }
}

HairSalon/Views/Clients/Add.cshtml
@{
  Layout = "_Layout";
}

@using HairSalon.Models
@model HairSalon.Models.Client

<h2>Add a new client here:</h2>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)
  
  @Html.LabelFor(model => model.Stylist)
  @Html.DropDownList("StylistId")

  <input type="submit" value="Add Client" />
}

<p>@Html.ActionLink("Back to Clients Page", "Index")</p>
<p>@Html.ActionLink("Back to Main Page", "Index", "Home")</p>

HairSalon/Views/Clients/Details.cshtml
@{
  Layout = "_Layout";
}

@using HairSalon.Models;
@model HairSalon.Models.Client


<h3>Name: @Html.DisplayFor(model => model.Name)</h3>
<h3> Stylist: </h3>
  <h5>@Html.DisplayFor(model => model.Stylist)</h5></li>


<p>@Html.ActionLink("Add a new client.", "Add")</p>
<p>@Html.ActionLink("Back to Client List Page", "Index")</p>
<p>@Html.ActionLink("Back to Main Page", "Index", "Home")</p>

HairSalon/Views/Clients/Index.cshtml
@{
  Layout = "_Layout";
}

@using HairSalon.Models;

<h1>Client summary:</h1>

<div class="index" id="home">
  @if (@Model.Count == 0)
  {
    <h3>No clients registered at the moment.</h3>
  } 

  <ul>
    @foreach(Client client in Model)
    {
      @if (@client.StylistId != 0)
      {
      <li>@Html.ActionLink($"{client.Name}", "Details", new { id = client.ClientId })</li>
      }
    }
  </ul>

  <p>@Html.ActionLink("Add a new client", "Add")</p>
  <p>@Html.ActionLink("Back to Main Page", "Index", "Home")</p>
</div>

HairSalon/Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}


  <h1>Welcome to Eau Claire's Salon - Online Management System</h1>
  <h2>Main Page</h2>

<div class="index" id="home">
  <h4>Select below to:</h4>

  <div class="options">
    <h5>Stylists:</h5>
    <p>@Html.ActionLink("View Stylists Page.", "Index", "Stylists")</p>

    <h5>Clients:</h5>
    <p>@Html.ActionLink("View Clients Page", "Index", "Clients")</p>
  </div>
</div>

HairSalon/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
  <head>
    <title>Hair Salon Management System</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link href="~/css/styles.css" rel="stylesheet" type="text/css">
  </head>
  <body>
    <div class="container">
      @RenderBody()
    </div>
  </body>
</html>

HairSalon/Views/Stylists/Add.cshtml
@{
  Layout = "_Layout";
}
@model HairSalon.Models.Stylist

<h2>Add a new stylist here:</h2>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)

  @Html.LabelFor(model => model.Skill);
  @Html.TextBoxFor(model => model.Skill)
  <input type="submit" value="submit stylist" />
}

<p>@Html.ActionLink("Back to Stylists Page", "Index")</p>
<p>@Html.ActionLink("Back to Main Page", "Index", "Home")</p>

HairSalon/Views/Stylists/Details.cshtml
@{
  Layout = "_Layout";
}

@using HairSalon.Models;
@model HairSalon.Models.Stylist


<h3>Name: @Html.DisplayFor(model => model.Name)</h3>

<div class="index" id="employee-details">
  <h4>Employee ID: @Html.DisplayFor(model => model.StylistId)</h4>
  <h4>Speciality/Skill: @Html.DisplayFor(model => model.Skill)</h4>
</div>

<h4>Current clients:</h4>

<div class="index" id="client-list">
  @if (Model.ClientList.Count == 0)
  {
    <h4>@Html.DisplayFor(model => model.Name) has no clients assigned at the moment.</h4>
  }

  @foreach (Client client in Model.ClientList)
  {
    <h4>@Html.ActionLink($"{client.Name}", "Details", "Clients", new { id = client.ClientId })</h4>
  }
</div>

<p>@Html.ActionLink("Add a new client.", "AddClient")</p>
<p>@Html.ActionLink("Back to Stylists Page", "Index")</p>
<p>@Html.ActionLink("Back to Main Page", "Index", "Home")</p>

HairSalon/Views/Stylists/Index.cshtml
@{
  Layout = "_Layout";
}

@using HairSalon.Models;

<h1>Stylists</h1>
<div class="index" id="home">
  @if (@Model.Count == 0)
  {
    <h3>No stylists have been hired yet.</h3>
    <h3>Please hire a stylist.</h3>
  } 

  <ul>
    @foreach(Stylist stylist in Model)
    {
      <li>@Html.ActionLink($"{stylist.Name}", "Details", new { id = stylist.StylistId })</li>
    }
  </ul>

  <p>@Html.ActionLink("Add a new Stylist", "Add")</p>
  <p>@Html.ActionLink("Back to Main Page", "Index", "Home")</p>
</div>

HairSalon/Views/Stylists/SelectStylist.cshtml
@{
  Layout = "_Layout";
}

@* @using HairSalon.Models; *@
@model HairSalon.Models.HairSalonContext;

<h1>Stylist selection:</h1>

<div class="index" id="home">

  @* <p>@Html.ActionLink("Add a new stylist", "Add")</p> *@
  <p>@Html.ActionLink("Back to Main Page", "Index", "Home")</p>
</div>